project_id = "qjfhyqjgqutkabxaeopi"

[functions.orlando-assistant]
verify_jwt = false

[functions.notify-new-user]
verify_jwt = false

[functions.notify-access-enabled]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-asaas-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.generate-personalized-itinerary]
verify_jwt = false

[functions.suggest-tickets]
verify_jwt = false

[functions.suggest-hotels]
verify_jwt = false

[functions.suggest-restaurants]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.notify-park-day]
verify_jwt = false

[functions.utalk-webhook]
verify_jwt = false

[functions.notify-abandoned-cart]
verify_jwt = false